<a href="https://colab.research.google.com/github/migue-3/Proyectos_Python/blob/main/Copia_de_Python_TOTAL_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica de la librería Numpy

En este notebook, se desarrollarán una serie de tareas utilizando la librería Numpy (Numerical Python).

Se proponen y documentan posibles formas de resolver los ejercicios, pero las mismas no son únicas.

Siempre es una buena idea verificar la [Documentación Oficial de Numpy](https://numpy.org/devdocs/user/index.html), donde es posible encontrar todo tipo de información referida a esta librería. Y si te quedas trabado, busca en Google "como hacer [algo] con Numpy". Hay enormes probabilidades de que esa pregunta ya haya sido respondida!

In [ ]:
# Importamos Numpy con su abreviación "np"
import numpy as np

In [ ]:
# Podemos crear arrays de una dimensión con la función np.array()
arr_1d = np.array([1,2,3,4,5])

# O un array de dos dimensiones (bidimensional)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# O un array de tres dimensiones (tridimensional)
arr_3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])




Para cada uno de estos arrays, podemos obtener sus propiedades, tales como su "forma", número de dimensiones, tipos de datos y tamaño.

In [ ]:
# Atributos del array unidimensional (forma, número de dimensiones, tipos de datos, tamaño, y tipo)
arr_1d.shape, arr_1d.ndim, arr_1d.dtype, arr_1d.size, type(arr_1d)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Atributos del array bidimensional
arr_2d.shape, arr_2d.ndim, arr_2d.dtype, arr_2d.size, type(arr_2d)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Atributos del array tridimensional
arr_3d.shape, arr_3d.ndim, arr_3d.dtype, arr_3d.size, type(arr_3d)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# Importamos pandas como pd, y creamos un DataFrame a partir del array bidimensional
import pandas as pd

datos = pd.DataFrame(arr_2d)
datos

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Creamos un array de tamaño 4x3, formado únicamente por unos (1)
unos = np.ones((4, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Creamos un array de tamaño 2x4x3, formado únicamente por ceros (0)
ceros = np.zeros((2, 4, 3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Creamos un array de números en el rango de 0 a 100, con un paso de 5
arr_1 = np.arange(0, 101, 5)
arr_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (2, 5)
arr_2 = np.random.randint(0, 10, (2, 5))
arr_2


array([[5, 1, 9, 9, 0],
       [4, 1, 6, 2, 3]])

In [ ]:
# Creamos un array de números aleatorios decimales comprendidos en entre 0 y 1, de tamaño (3, 5)
arr_3 = np.random.random((3, 5))
arr_3

array([[0.12370653, 0.19661292, 0.03281387, 0.38533745, 0.61509647],
       [0.26889082, 0.16411728, 0.95852883, 0.97620676, 0.94101677],
       [0.71891442, 0.24898552, 0.06910699, 0.45651319, 0.50234779]])

In [ ]:
# Establecemos la "semilla" de números aleatorios en 27
np.random.seed(32)

# Creamos un array de números aleatorios enteros comprendidos en entre 0 y 10, de tamaño (3, 5)
arr_4 = np.random.randint(0, 10, (3, 5))
arr_4


array([[7, 5, 6, 8, 3],
       [7, 9, 3, 5, 9],
       [4, 1, 3, 1, 2]])

¿Qué ocurre al correr la última celda nuevamente, a diferencia de las anteriores?

In [ ]:
# Encontramos los valores únicos del array_4
np.unique(arr_4)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Extraemos el elemento de índice 1 del array_4
arr_4[1]

array([7, 9, 3, 5, 9])

In [ ]:
# Extraemos las primeras dos filas del array_4
arr_4[:2]

array([[7, 5, 6, 8, 3],
       [7, 9, 3, 5, 9]])

In [ ]:
# Extraemos los dos primeros datos de las primeras dos filas del array_4
arr_4[:2, :2]

array([[7, 5],
       [7, 9]])

In [ ]:
# Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
arr_5 = np.random.randint(0, 10, (3, 4))
arr_6 = np.ones((3, 4))


In [ ]:
# invocamos el array_5
arr_5

array([[4, 0, 6, 4],
       [9, 0, 3, 2],
       [5, 3, 2, 8]])

In [ ]:
# invocamos el array_6
arr_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Sumamos los dos arrays
arr_5 + arr_6

array([[ 5.,  1.,  7.,  5.],
       [10.,  1.,  4.,  3.],
       [ 6.,  4.,  3.,  9.]])

In [ ]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
arr_7 = np.ones((4, 3))
arr_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Intentaremos sumar los arrays 6 y 7
arr_6 + arr_7.T


array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

¿A qué se debe el error anterior? ¿Qué deberíamos tener en cuenta para que no suceda?

In [ ]:
# Entonces crearemos otro array de tamaño (4,3) lleno de unos
arr_8 = np.ones((4, 3))
arr_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Restamos el array_8 al array_7
arr_8 - arr_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Creamos otros dos arrays de tamaño 3x3 con números aleatorios del 1 al 5
arr_9 = np.random.randint(1, 5, (3, 3))
arr_10 = np.random.randint(1, 5, (3, 3))

In [ ]:
# invocamos el array_9
arr_9

array([[4, 4, 4],
       [2, 4, 4],
       [4, 3, 3]])

In [ ]:
# invocamos el array_10
arr_10

array([[2, 4, 2],
       [1, 1, 1],
       [1, 3, 2]])

In [ ]:
# Multiplicamos los últimos dos arrays entre sí
arr_9 * arr_10

array([[ 8, 16,  8],
       [ 2,  4,  4],
       [ 4,  9,  6]])

In [ ]:
# Elevamos el array_9 al cuadrado
arr_9 ** 2

array([[16, 16, 16],
       [ 4, 16, 16],
       [16,  9,  9]])

In [ ]:
# Buscamos la raíz cuadrada del array_10
np.sqrt(arr_10)

array([[1.41421356, 2.        , 1.41421356],
       [1.        , 1.        , 1.        ],
       [1.        , 1.73205081, 1.41421356]])

In [ ]:
# Hallamos el promedio de los valores del array_9
np.mean(arr_9)

3.5555555555555554

In [ ]:
# Hallamos el valor máximo de los valores del array_9
arr_9.max()

4

In [ ]:
# Hallamos el valor mínimo de los valores del array_9
arr_9.min()

2

In [ ]:
# Cambiamos la forma del array_9 por una de 9x1, y lo almacenamos como array_11
arr_11 = arr_9.reshape(9, 1)

In [ ]:
# invocamos el array_11
arr_11

array([[4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [3],
       [3]])

In [ ]:
# Transponemos el array_11
arr_11.T

array([[4, 4, 4, 2, 4, 4, 4, 3, 3]])

In [ ]:
# Comparamos el array_9 y el array_10, para saber cuáles elementos del array_9 son mayores a los del array_10
arr_12 = arr_9 > arr_10
arr_12

array([[ True, False,  True],
       [ True,  True,  True],
       [ True, False,  True]])

¿Qué tipos de datos forman parte del array de resultados?

In [ ]:
# Veamos sus nuevos tipos de datos
arr_12.dtype

dtype('bool')

In [ ]:
# Alguno de los elementos del array_9 es igual su equivalente del array_10?
arr_9 == arr_10

array([[False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [ ]:
# Comparamos nuevamente ambos arrays, en esta ocasión con >=
arr_9 >= arr_10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Buscamos los elementos del array_9 que son mayores a 2
arr_9 > 2

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Ordenamos de menor a mayor los elementos dentro del array_9
np.sort(arr_9)

array([[4, 4, 4],
       [2, 4, 4],
       [3, 3, 4]])